export const addressComponents = [
  { title: "Street Number", description: "552" },
  { title: "Street Name", description: "N Orchard Drive" },
  { title: "Zip Code", description: "84116" },
  { title: "+4 Code", description: "1334" },
  { title: "City", description: "Salt Lake City" },
  { title: "State", description: "UT" },
  { title: "Longitude", description: "-111.876543" },
  { title: "Latitude", description: "40.765432" },
  { title: "County", description: "Salt Lake County" },
  { title: "Country", description: "USA" },
  { title: "Time Zone", description: "Mountain" },
  { title: "Carrier Route", description: "C00112" },
  { title: "Delivery Point", description: "1234" },
  { title: "Unit Type", description: "APT" },
  { title: "Unit Number", description: "123" },
  { title: "Congressional District", description: "07" },
  { title: "RDI", description: "Residential" },
  { title: "Vacant", description: "No" },
];
